# Generated by Django 5.2.7 on 2025-10-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park', models.CharField(choices=[('KP', "King's Park"), ('LP', 'Linn Park'), ('RG', 'Rouken Glen'), ('PP', 'Pollock Park'), ('BP', 'Bellahouston Park'), ('QP', "Queen's Park")], max_length=2)),
            ],
        ),
    ]
