# Generated by Django 5.2.7 on 2025-10-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_season_alter_race_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='park',
            field=models.CharField(choices=[('KP', "King's Park"), ('LP', 'Linn Park'), ('RG', 'Rouken Glen'), ('PP', 'Pollok Park'), ('BP', 'Bellahouston Park'), ('QP', "Queen's Park")], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='race',
            unique_together={('park', 'season')},
        ),
    ]
