# Generated by Django 5.2.7 on 2025-10-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0007_alter_race_park_alter_race_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='season_start_year',
            new_name='season',
        ),
    ]
