# Generated by Django 5.2.7 on 2025-10-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_rename_season_start_year_season_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
