# Generated by Django 5.2.7 on 2025-10-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0009_alter_season_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
