# Generated by Django 5.2.7 on 2025-10-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_race_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(help_text='For 2025/2026 season, enter 2526', max_length=4, unique=True),
        ),
    ]
