# Generated by Django 5.2.7 on 2025-10-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0012_remove_result_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='full_name',
        ),
        migrations.AddField(
            model_name='runner',
            name='first_name',
            field=models.CharField(default='dummy', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runner',
            name='last_name',
            field=models.CharField(default='dummy', max_length=256),
            preserve_default=False,
        ),
    ]
