# Generated by Django 5.2.7 on 2025-10-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0013_remove_runner_full_name_runner_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='category',
            field=models.CharField(default='MS', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runner',
            name='club',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='runner',
            name='participant_number',
            field=models.CharField(default='1', max_length=5),
            preserve_default=False,
        ),
    ]
