# Generated by Django 5.2.7 on 2025-10-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0014_runner_category_runner_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='category',
            field=models.CharField(max_length=4),
        ),
    ]
