# Generated by Django 5.2.7 on 2025-10-19 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0016_alter_runner_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XLSX', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['xlsx'])])),
            ],
        ),
    ]
