# Generated by Django 5.2.7 on 2025-10-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0017_racefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racefile',
            old_name='XLSX',
            new_name='excel_file',
        ),
    ]
