# Generated by Django 5.2.7 on 2025-10-21 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0018_rename_xlsx_racefile_excel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.season')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_points', models.IntegerField(null=True)),
                ('gender_points', models.IntegerField(null=True)),
                ('category_points', models.IntegerField(null=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.classification')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.runner')),
            ],
        ),
    ]
