# Generated by Django 5.2.7 on 2025-10-21 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0019_classification_classificationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='race',
            field=models.ForeignKey(default=149, on_delete=django.db.models.deletion.CASCADE, to='races.race'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RecalculatedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(blank=True, null=True)),
                ('points', models.IntegerField(null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.runner')),
            ],
        ),
    ]
