# Generated by Django 5.2.7 on 2025-10-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0020_classification_race_recalculatedresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recalculatedresult',
            name='time',
        ),
    ]
