# Generated by Django 5.2.7 on 2025-10-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0021_remove_recalculatedresult_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
