# Generated by Django 5.2.7 on 2025-10-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0022_classification_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recalculatedresult',
            name='points',
        ),
        migrations.AddField(
            model_name='recalculatedresult',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
