# Generated by Django 5.2.7 on 2025-10-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0023_remove_recalculatedresult_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='racefile',
            name='contents',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='RecalculatedResult',
        ),
    ]
