# Generated by Django 5.2.7 on 2025-10-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0024_racefile_contents_delete_recalculatedresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racefile',
            name='contents',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
