# Generated by Django 5.2.7 on 2025-10-26 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0025_alter_racefile_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='racefile',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='races.race'),
        ),
    ]
